export const seedData = [
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01230857415",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Akkelpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01596668249",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Akkelpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01673190142",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Akkelpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 2, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01129903693",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Akkelpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 5, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01305503344",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Akkelpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01142005212",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Akkelpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 3, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01112815528",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01169635261",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01229683238",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01425669473",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 9, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01505827512",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 1, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01605635225",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 4, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01945234067",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 3, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01548262883",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 2, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01870402038",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, Ibn Sina Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01631115065",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Bambal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 4, Central Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01295075243",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01335233324",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 9, Labaid Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01302102701",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 9, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01975189635",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01155947256",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01557779927",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01100893441",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01333929636",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 6, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01993120318",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Joypurhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01500320703",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01966632596",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 3, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01625826053",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01724651251",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01250528596",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 9, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01364028028",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01553035170",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 10, Marks Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01332078419",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01733890385",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 4, Marks Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01487268455",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Kalai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01190935854",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Khetlal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 1, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01652145110",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Khetlal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01946592568",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Khetlal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01848710191",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Khetlal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 6, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01214651903",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Khetlal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01483286895",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Khetlal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01559745176",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Khetlal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 2, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01964901324",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 2, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01264897949",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01931086426",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01398850448",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 7, Apollo Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01459022842",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 9, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01879238920",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01391961478",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01107564119",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01963647927",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Joypurhat",
    subDistrict: "Panchbibi",
    status: "Open",
    isSeed: true,
  },
];
