export const seedData = [
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 3, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01358326442",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 2, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01833680965",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 3, Labaid Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01888160863",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01675269822",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01886053206",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 3, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01177295149",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 1, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01795686630",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01758415699",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01751538505",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01767854407",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01145653447",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 3, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01985160887",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01127595830",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01770919680",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01345006411",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 1, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01319992958",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 3, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01978803835",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01328352424",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01918669725",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01377832697",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01854983611",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01405340374",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01854118118",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01293642219",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 10, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01446161092",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01358882263",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01896907705",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01150457979",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01597272752",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 5, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01265502226",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01618123951",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 7, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01471595451",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 10, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01941136459",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01737319272",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01188154304",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 9, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01789041700",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01466811965",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01852601705",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 1, BIRDEM General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01993934679",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 2, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01710014818",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 2, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01613567950",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 8, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01846823961",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01418165258",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01778703789",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 1, BIRDEM General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01823177763",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01867917674",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01340041335",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01776235378",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 8, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01101767305",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01791941207",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 2, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01987240045",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01485453899",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 7, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01397023579",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01905164257",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
];
