export const seedData = [
  {
    patientName: "Arifa Sultana",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01925395226",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01316528687",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01856718788",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01322957736",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 3, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01672243921",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 10, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01919441910",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01869273428",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 5, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01694965378",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Bhurungamari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01270552160",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 6, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01513323482",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01549980549",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 8, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01131569392",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01818892090",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01109985867",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 8, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01752828837",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 2, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01794404016",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Char Rajibpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01825706394",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Chilmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01373137276",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Chilmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01407907948",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Chilmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01946173404",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Chilmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 10, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01975525407",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Chilmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01359984070",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Chilmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01388728693",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Chilmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01606054348",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01969558331",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 5, Central Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01121856730",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01415085030",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, MH Samorita Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01769168697",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 6, Marks Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01375800613",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01943073441",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 7, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01964929160",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01817727721",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Kurigram Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01737142612",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 6, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01821753540",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01291055334",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 9, BIRDEM General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01866223040",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01213440473",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01547441739",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01779592352",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 2, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01710246894",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Nageshwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 3, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01509642819",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Phulbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01691706353",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Phulbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01252140356",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Phulbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 1, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01839598350",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Phulbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01422643569",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Phulbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01219869415",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Rajarhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01258734744",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Rajarhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 7, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01101930849",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Rajarhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 6, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01821513482",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Rajarhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01971328884",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Rajarhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01759363131",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Rajarhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01620390449",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01899483706",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01495183709",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, Ibn Sina Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01474137052",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01451860381",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 6, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01653202617",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, Delta Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01694114145",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01203069812",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01616024404",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Raomari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01949625398",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01104747937",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01889369992",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01736238157",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01525166144",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01211584694",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 10, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01862812998",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 3, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01399536551",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01674711873",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Kurigram",
    subDistrict: "Ulipur",
    status: "Open",
    isSeed: true,
  },
];
