export const seedData = [
  {
    patientName: "Jesmin Akter",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01756768722",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 9,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01439745034",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 32,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 2, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01298561727",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 21,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 9, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01672528549",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 56,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 5, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01857989543",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01230773085",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 6, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01166449187",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 23,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01275093718",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 10,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01698953803",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 26,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 5, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01465423953",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 45,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01893058575",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 38,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 6, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01972090387",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 36,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01775599057",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 16,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01368985251",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 50,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01269104071",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 6, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01452970698",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 37,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 9, BRB Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01370029951",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 9,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01542899340",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 20,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 5, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01552820663",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 9,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01220492329",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 39,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 2, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01877360068",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 25,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 9, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01427681533",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 29,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01383001061",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01230974856",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 38,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01983852531",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 36,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01295740961",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 7,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 7, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01694085662",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 22,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01791335482",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 28,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01109837164",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 57,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, MH Samorita Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01658142628",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 35,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 8, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01225769667",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 33,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01574078600",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 21,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01461930826",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 42,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, Delta Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01500137971",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 5,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 10, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01724744186",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 38,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 9, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01369460109",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 64,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01903087327",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 41,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 8, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01603572414",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "Male",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01184378466",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 22,
    patientGender: "Female",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01422374388",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 52,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01495892110",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 50,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 6, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01985973814",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 57,
    patientGender: "Other",
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
];
