export const seedData = [
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01927453033",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01101232168",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01695164007",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01313625005",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01310606449",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Aditmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 4, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01618119946",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 9, Marks Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01791244111",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 2, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01684642654",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 1, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01368640082",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01420799008",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01906273810",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 8, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01740625601",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 3, BRB Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01835202113",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Hatibandha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01509629634",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01121515208",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01730029088",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01228587330",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01897027280",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01678431298",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 1, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01293117439",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01177086974",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 9, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01426115371",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01265322716",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01520340229",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01162778996",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01941661237",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01929331039",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01154092958",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Lalmonirhat Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01932444036",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01785253370",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01660485169",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01555407947",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01550978172",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 3, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01839515495",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01780547510",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Lalmonirhat",
    subDistrict: "Patgram",
    status: "Open",
    isSeed: true,
  },
];
