export const seedData = [
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01559434257",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 9,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Dimla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 2, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01953309304",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 51,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Dimla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01868028256",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 50,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Dimla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 8, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01839844301",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 33,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Dimla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01475190892",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 37,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Dimla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01636798549",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 26,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Dimla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01662134688",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 48,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01793300803",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 64,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 6, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01433722234",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 10,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 2, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01294605773",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 25,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01555628836",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 24,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01723244651",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 41,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01263650601",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 49,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01169359309",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 62,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01767958546",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 21,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01702630690",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 41,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Domar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01384110171",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 13,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01595876660",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 57,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01722980962",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 46,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01254074604",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 57,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 8, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01316004655",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 13,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01509909265",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 53,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 2, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01449296043",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01426617606",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 62,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01937456102",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 33,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Jaldhaka",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01242356459",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 61,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01389066896",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 50,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01679559573",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 11,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01563797514",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 36,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01197015580",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 10, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01941603247",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 55,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01457622373",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 8,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01977196928",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 26,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01133305266",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 40,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Kishoreganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01107721813",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 26,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Nilphamari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 6, Apollo Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01152360644",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 14,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Nilphamari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01533464649",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 20,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Nilphamari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01738300613",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 40,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Nilphamari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01815761520",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 6,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Nilphamari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01752790156",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 60,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 10, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01586151013",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 5,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01140007390",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 48,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01649582427",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 41,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01456394003",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 20,
    patientGender: "Male",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01645845576",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 57,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01781640677",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 35,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01441672344",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 19,
    patientGender: "Other",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01563065009",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 52,
    patientGender: "Female",
    division: "Rangpur",
    district: "Nilphamari",
    subDistrict: "Saidpur",
    status: "Open",
    isSeed: true,
  },
];
