export const seedData = [
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01676167468",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 15,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01770109957",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 31,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 10, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01772653423",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 28,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01848389620",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 23,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 10, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01815976648",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 6,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01722142608",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 5,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01312191552",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 52,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 8, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01453005592",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 47,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01699015068",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 15,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 5, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01238045941",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 7,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Atwari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01318487037",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 55,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Boda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01110908745",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 53,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Boda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 10, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01868596254",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 29,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Boda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 3, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01395773890",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 21,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Boda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Apollo Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01925710835",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 26,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Boda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01133320588",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 27,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01493535474",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 48,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01803388243",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 64,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01601685455",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 26,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01406924053",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 42,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 6, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01854342878",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 28,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 3, Ibn Sina Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01823960546",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 61,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01313495269",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 45,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Debiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01433380652",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 14,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01271088609",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 50,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01179780692",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 11,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01122077615",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 21,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01675296623",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01374824961",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 11,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01231643721",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 50,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01166055056",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 38,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01372398130",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 7, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01369941899",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Panchagarh Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 2, Central Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01733598377",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 15,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Tetulia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01589250247",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 45,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Tetulia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 1, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01805209338",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 49,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Tetulia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01743796350",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 45,
    patientGender: "Female",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Tetulia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01231945723",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 38,
    patientGender: "Male",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Tetulia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 10, Kurmitola General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01526912252",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 30,
    patientGender: "Other",
    division: "Rangpur",
    district: "Panchagarh",
    subDistrict: "Tetulia",
    status: "Open",
    isSeed: true,
  },
];
