export const seedData = [
  {
    patientName: "Habibur Rahman",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 4, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01980210321",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Badarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 3, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01444942289",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Badarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01528933705",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Badarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01156359304",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Badarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 5, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01678233495",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Badarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01275069705",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01680984069",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01227166995",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01962085591",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 2, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01900711977",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01446143522",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01782817137",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01266702540",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01445744950",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Gangachara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01463001667",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Kaunia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 7, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01462205740",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Kaunia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 8, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01302052225",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Kaunia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01439324688",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Kaunia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01985386628",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Kaunia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 9, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01519278010",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Kaunia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 9, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01536947283",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 10, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01979353009",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01574252659",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 9, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01375816519",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01754781143",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01942433440",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01269880892",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Kurmitola General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01622295161",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01318036928",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Mithapukur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01875876185",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01843711514",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 7, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01695592917",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 6, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01321888767",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 6, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01923483610",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01151687358",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01453643958",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01471325055",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01752317325",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01444542319",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01961665316",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 9, United Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01271487553",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01920688581",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01825004875",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Rangpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01828633236",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Rangpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 8, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01347715204",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Rangpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 8, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01409375671",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Rangpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01494760501",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Rangpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01103066905",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Rangpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 10, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01968963498",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01904259444",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01168802004",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01279473960",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01113999887",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01902399631",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 5, MH Samorita Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01553537245",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, BRB Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01236160858",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 8, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01949407469",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rangpur",
    district: "Rangpur",
    subDistrict: "Taraganj",
    status: "Open",
    isSeed: true,
  },
];
