export const seedData = [
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 9, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01891251683",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 62,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Chandpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01111982906",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 6,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Chandpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 10, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01200897948",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 28,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Chandpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 6, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01980594959",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 25,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Chandpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01336043819",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 36,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Chandpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 7, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01866436022",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 42,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Chandpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 6, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01956721589",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 60,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Chandpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01634532127",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 14,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Faridganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01674252928",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 10,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Faridganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 6, Evercare Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01520790043",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 22,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Faridganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01148431406",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 55,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Faridganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01486958682",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 57,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Faridganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01924217161",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 22,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Faridganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01791516593",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 29,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Faridganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01222639491",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 24,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01876488843",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 29,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 10, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01165303910",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 8,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01208429776",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 62,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01352925274",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 7,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01989203902",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 5,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01175493672",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01359491845",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 52,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01794994186",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 4, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01752661625",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 23,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haimchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 2, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01772751226",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 42,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haziganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01365124566",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 27,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haziganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01205965178",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 28,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haziganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 4, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01599021973",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 31,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haziganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01753102409",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 31,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haziganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01832626364",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 33,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haziganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01664727066",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 62,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Haziganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01643791555",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 26,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01875410127",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 41,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01791867727",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 34,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01619485169",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 40,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01521733358",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 61,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01848423693",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 62,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01191172634",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 54,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01531781859",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 5,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01226522950",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 31,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Kachua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01152113945",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 34,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab North",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01915737820",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 51,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab North",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01454446379",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 5,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab North",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01461724367",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 47,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab North",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 3, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01611625655",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 36,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab North",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01456153506",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 14,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab North",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01279952454",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 23,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab North",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01313438916",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 57,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01976848517",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 43,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01576778316",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 37,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 6, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01653307356",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 59,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01621098795",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 16,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01873505422",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 42,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01185862261",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 16,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01474924468",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 5,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01790131254",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 7,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Matlab South",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01473744214",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 50,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01618985210",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 30,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01175708407",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 36,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01809608781",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 19,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 7, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01712955205",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 62,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01953642173",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 43,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 2, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01176055145",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 6,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 6, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01258777841",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 21,
    patientGender: "male",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01540188919",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 49,
    patientGender: "female",
    division: "Chittagong",
    district: "Chandpur",
    subDistrict: "Shahrasti",
    status: "Open",
    isSeed: true,
  },
];
