export const seedData = [
  {
    patientName: "Tania Ahmed",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01921067664",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 40,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01388325363",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 50,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01439387467",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 59,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 6, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01340991406",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 29,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01575491496",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 19,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01873467156",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 37,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01361496386",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 5,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01302240421",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 62,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01856647540",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 33,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01177934028",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 48,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Chakaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01639754707",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 27,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Cox's Bazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01595010513",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 6,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Cox's Bazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 7, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01345859451",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 50,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Cox's Bazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 8, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01598557097",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 31,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Cox's Bazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01458306779",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 33,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Cox's Bazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 5, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01818654637",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 33,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Eidgaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 10, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01236182497",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Eidgaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01406384222",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 63,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Eidgaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01542042512",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 54,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Eidgaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01196278966",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Eidgaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01893920305",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Kutubdia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01598035909",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 29,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Kutubdia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 3, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01884088535",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 36,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Kutubdia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 6, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01271211420",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 51,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Kutubdia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01966581203",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Kutubdia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01356664229",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 36,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Kutubdia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01305020357",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 6,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01147793664",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 10,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 7, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01805253839",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 45,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01273137542",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 8,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01477584660",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 48,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01462224362",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 54,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01384802014",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 23,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01755258724",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 13,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Maheshkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 10, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01598846457",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 49,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01837500629",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 28,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 7, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01590801920",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 57,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01889707483",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 5,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 5, Enam Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01510115997",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 23,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01509053376",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 14,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 9, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01656476725",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 20,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01677718636",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 41,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01433191107",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 8, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01439758892",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 55,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Pekua",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01314004061",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 25,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01868788154",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 33,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 7, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01760191245",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 22,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 3, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01481671780",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 10,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 6, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01943172281",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 43,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01610777864",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 9,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01529392922",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 36,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01604950565",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 54,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ramu",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 1, Square Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01166562668",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 8,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Teknaf",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01128062983",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 22,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Teknaf",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 5, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01924970132",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 53,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Teknaf",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01838958391",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 40,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Teknaf",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01838012951",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 25,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Teknaf",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01320342290",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 15,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Teknaf",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01526223373",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 8,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Teknaf",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 3, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01123934363",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 58,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ukhia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01888571724",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 49,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ukhia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 8, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01206005631",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 13,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ukhia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01904180225",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 19,
    patientGender: "male",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ukhia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01811782336",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 43,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ukhia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 9, BRB Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01993793216",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 33,
    patientGender: "female",
    division: "Chittagong",
    district: "Cox's Bazar",
    subDistrict: "Ukhia",
    status: "Open",
    isSeed: true,
  },
];
