export const seedData = [
  {
    patientName: "Jahangir Alam",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 24,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 53,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 9,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 53,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 6, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 7,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 5,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 36,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 52,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 31,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Dighinala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 5, Evercare Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 56,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 6,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 11,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 10, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 36,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 9, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 10,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 50,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 58,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 28,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Guimara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 35,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Khagrachhari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 56,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Khagrachhari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 59,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Khagrachhari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 64,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Khagrachhari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Khagrachhari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 45,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Lakshmichhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 36,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Lakshmichhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 9, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 47,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Lakshmichhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 10, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 11,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Lakshmichhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 16,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Lakshmichhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 41,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, Apollo Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 56,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 41,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 55,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 60,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 37,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 5, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 29,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 5, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 33,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 2, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 60,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 57,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Mahalchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 6, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 29,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Manikchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 20,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Manikchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 12,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Manikchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 56,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Manikchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 23,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Manikchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 5, Evercare Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 12,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Manikchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 59,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Manikchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Matiranga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 46,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Matiranga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 32,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Matiranga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 10, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 29,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Matiranga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 48,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Matiranga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 24,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 64,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 30,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 3, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 15,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 36,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 11,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 4, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 28,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Panchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 32,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Ramgarh",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 7, BRB Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 21,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Ramgarh",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 38,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Ramgarh",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 17,
    patientGender: "Male",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Ramgarh",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 6, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 13,
    patientGender: "Female",
    division: "Chittagong",
    district: "Khagrachhari",
    subDistrict: "Ramgarh",
    status: "Open",
    isSeed: true,
  },
];
