export const seedData = [
  {
    patientName: "Shafiqul Alam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 7, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 15,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 13,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 9, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 13,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 7, Marks Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 10,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 49,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 38,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 21,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 41,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 54,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 53,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, Evercare Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 55,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 4, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 32,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 3, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 49,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 64,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, MH Samorita Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 60,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 14,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 2, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 22,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 20,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 2, Apollo Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 56,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 10, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 19,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 38,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, Evercare Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 46,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 46,
    patientGender: "Male",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 31,
    patientGender: "Female",
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
];
