export const seedData = [
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01119883324",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 56,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Abhaynagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01938796158",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 62,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Abhaynagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01984268051",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 5,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Abhaynagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01466257645",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 47,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Abhaynagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700536127",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 30,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Abhaynagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01551464153",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 13,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Abhaynagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 9, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01106651268",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 25,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Abhaynagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01175459520",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 14,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 7, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01846785294",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 39,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01575461155",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 36,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01274143335",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 41,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01248070181",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 18,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01789284724",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 15,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01370821218",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 26,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 8, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01230566528",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01591337275",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 30,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 2, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01318829016",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 62,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Bagherpara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01133958238",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 60,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01602958839",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 30,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01877364547",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 56,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01365305144",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 44,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01898861207",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 18,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01555345488",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 19,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01791066293",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 46,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01288691975",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 46,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01778123094",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 64,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 10, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01590090957",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 14,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Chaugachha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01538685558",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 62,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 3, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01465134844",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 38,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01975710657",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 43,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 1, Square Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01833565569",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 29,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01749118672",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 46,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01864480104",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 46,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01971714332",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 63,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01540590426",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 17,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01301487032",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 10,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 9, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01659759511",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 58,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jhikargacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01263958889",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01953286079",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 52,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01753469545",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 64,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01658986360",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 57,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01240669099",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 14,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01578156418",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 38,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01309380556",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 51,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01595370723",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 22,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 9, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01794532833",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 28,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Keshabpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01914134160",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01345927697",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 21,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01788083541",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 16,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01787229995",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 54,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01117376605",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 28,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01718247033",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 45,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01475528433",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 33,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 3, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01747659691",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 33,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01299010262",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Jessore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01689483614",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 7,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01705449305",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 23,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01219574072",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 60,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01570503057",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 54,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01915648854",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 61,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01109750606",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 18,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, Evercare Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01941193300",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 36,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01197725461",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 7,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Manirampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01443191028",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 9,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Sharsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01632362280",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 36,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Sharsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01697827217",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 38,
    patientGender: "female",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Sharsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01193778250",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Sharsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01797315578",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 64,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Sharsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01182320496",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 50,
    patientGender: "male",
    division: "Khulna",
    district: "Jessore",
    subDistrict: "Sharsha",
    status: "Open",
    isSeed: true,
  },
];
