export const seedData = [
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01319866532",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 54,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Harinakunda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 4, Central Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01502019806",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 32,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Harinakunda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01509350431",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Harinakunda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01155143463",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 23,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Harinakunda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01765292089",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 5,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Harinakunda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01479504490",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 55,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01609073824",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 38,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 5, Evercare Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01254754380",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 55,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 6, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01289016478",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 15,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01688448666",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01354452805",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 48,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01259305649",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 57,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 4, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01237750955",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 18,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01750439493",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 22,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Jhenaidah Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 10, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01980484145",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 11,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01276150686",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 7, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01612942580",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 57,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 6, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01100239358",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 50,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01299173734",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 30,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01391380102",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 38,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01172716004",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 55,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01941485447",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 19,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01469283224",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 42,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01241335085",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 40,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01634065822",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 32,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kotchandpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, Evercare Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01481840954",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 26,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kotchandpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 8, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01651925409",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 60,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kotchandpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01463948399",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 46,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kotchandpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01877235411",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 42,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kotchandpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01343989175",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 56,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kotchandpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01646089458",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 40,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Kotchandpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01196730423",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 58,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01981347427",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 17,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01510097417",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 41,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01625918882",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 32,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01232282473",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 44,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 3, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01845812500",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 17,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01206843426",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 30,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01676193636",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 31,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01436657171",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 21,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Maheshpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 1, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01160047272",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 22,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01454250449",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 20,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01423477680",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 55,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 6, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01787074558",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01358363337",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 60,
    patientGender: "Female",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01243477865",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 64,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01284359093",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 20,
    patientGender: "Male",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01623891252",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 58,
    patientGender: "Other",
    division: "Khulna",
    district: "Jhenaidah",
    subDistrict: "Shailkupa",
    status: "Open",
    isSeed: true,
  },
];
