export const seedData = [
  {
    patientName: "Meherun Nesa",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 5, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01922661695",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 23,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01972918891",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 54,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01507452439",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 29,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01242661961",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 52,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01349748827",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 42,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01247055444",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 64,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01908733275",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 59,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 8, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01628288937",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 42,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01849458192",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 50,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01653729628",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 23,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01169632013",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 6,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01595614135",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 51,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 8, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01847921896",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 10,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, Delta Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01201753604",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01832508059",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01934601123",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 40,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 3, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01848236618",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 4, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01276813841",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 57,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01746953305",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01511443106",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 10,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01291358296",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 59,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01689036107",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01406203267",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 20,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 8, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01852326096",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 20,
    patientGender: "Male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 7, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01868184294",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 56,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01817248924",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 19,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01127081460",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 61,
    patientGender: "Other",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01261524295",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 32,
    patientGender: "Female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
];
