export const seedData = [
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01245199331",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 9,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01743470826",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 17,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01249117032",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 52,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01491593414",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 34,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01280876948",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 64,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Magura Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, BRB Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01689785821",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 55,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01619773500",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 34,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 10, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01724560610",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 54,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 9, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01384660285",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 54,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01805822636",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 17,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 5, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01362965319",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 45,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 5, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01746539242",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 20,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Mohammadpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01979441080",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 15,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01471786148",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 7,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01575996534",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 34,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01799296282",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 40,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01852706477",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 30,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 9, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01964277689",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 57,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01918114568",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 36,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01655039445",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Shalikha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01753166762",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 34,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01771548669",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 30,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01136866670",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 14,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01893114993",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 10,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01289243390",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 9, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01638829450",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 15,
    patientGender: "male",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01349121792",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 51,
    patientGender: "female",
    division: "Khulna",
    district: "Magura",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
];
