export const seedData = [
  {
    patientName: "Monir Hossain",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01547800895",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 19,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01538274004",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 26,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 7, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01447401971",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01924913546",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 19,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01618573463",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 15,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01167785688",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 23,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 2, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01664080711",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 14,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 9, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01268288747",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 58,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 4, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01901182765",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 53,
    patientGender: "Female",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01728603004",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 40,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01749769807",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 60,
    patientGender: "Female",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01368125794",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 44,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 10, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01710330767",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 54,
    patientGender: "Female",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01556164359",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 60,
    patientGender: "Female",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 7, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01613736754",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 56,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01826381521",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 5,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01344665948",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 16,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01261289424",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 58,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01661731936",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 57,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 6, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01508268582",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 42,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01301466916",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 8,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 9, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01715696257",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 27,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Central Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01521114398",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 54,
    patientGender: "Other",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01126769297",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 28,
    patientGender: "Male",
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
];
