export const seedData = [
  {
    patientName: "Golam Mostafa",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 16,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Agailjhara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 44,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Agailjhara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 52,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Agailjhara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 38,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Agailjhara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 9, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 47,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Agailjhara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 54,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Agailjhara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 6, MH Samorita Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 8,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 23,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 22,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 22,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 20,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 7, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 32,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 38,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 60,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Babuganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 51,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Bakerganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 5, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 63,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Bakerganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 9, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 5,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Bakerganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 6, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 30,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Bakerganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 10,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Bakerganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 37,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 12,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 31,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 10, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 60,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 6,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Enam Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 22,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 40,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 7, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 11,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Banaripara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 24,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 6, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 45,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 9, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 51,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 62,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 2, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 57,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 1, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 56,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 15,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Barisal Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 58,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 46,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 6, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 38,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 34,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, United Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 51,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 10, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 45,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 55,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Gournadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Hizla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 49,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Hizla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 5, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 49,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Hizla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 64,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Hizla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 49,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Hizla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 28,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 9, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 53,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 31,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 4, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 23,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 64,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 28,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 13,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 44,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 28,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 8, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 22,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Mehendiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 52,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Muladi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 59,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Muladi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 3, Evercare Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 8,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Muladi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 46,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Muladi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Muladi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Muladi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 33,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Muladi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 7,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Uzirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 7, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 59,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Uzirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 7, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 21,
    patientGender: "Male",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Uzirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 1, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Uzirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 54,
    patientGender: "Female",
    division: "Barisal",
    district: "Barisal",
    subDistrict: "Uzirpur",
    status: "Open",
    isSeed: true,
  },
];
