export const seedData = [
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 9,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 6, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 48,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 10, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 52,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 56,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 60,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 8,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 31,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 10, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 49,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 35,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 37,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 52,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 5, MH Samorita Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 34,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 51,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 61,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 33,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 47,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 15,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 27,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 50,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 3, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 9,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 49,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 54,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 2, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 8,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 64,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 57,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 60,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 20,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 15,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 20,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 10, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 56,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 8, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 34,
    patientGender: "Male",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 8, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 45,
    patientGender: "Female",
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
];
