export const seedData = [
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 3, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01635357352",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 9, Marks Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01393124092",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, Square Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01530094793",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 1, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01535318421",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01215264114",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 1, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01101341956",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 2, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01220331805",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01548679417",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01783885209",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 6, Evercare Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01551951496",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01492287379",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01536380039",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01961271487",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01458261848",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01848201927",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01409648688",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 9, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01406978040",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 4, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01510809025",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01915988570",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 4, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01438624191",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, BIRDEM General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01855078451",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01266482248",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01349845393",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 4, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01761265327",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01604953100",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01503114726",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01921959970",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01123556674",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 10, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01199678289",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 10, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01631666618",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01578698481",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 10, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01284455102",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01885002396",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 7, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01911357840",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01840843022",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 10, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01665458326",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
];
