export const seedData = [
  {
    patientName: "Sadia Afrin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 10, Evercare Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01277349427",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 5,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01339556601",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 7, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01852774021",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 22,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 9, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01735447149",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 37,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01472589099",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 7,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 9, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01642955730",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 43,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 10, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01431120146",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 47,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01960010821",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 40,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 10, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01933321555",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01272268493",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 55,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01776071733",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 20,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01566082900",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 41,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01340730761",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 53,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01632594616",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 14,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01466989436",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 47,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01399110476",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 63,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01536191650",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 29,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01921790507",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 59,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 5, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01954061883",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 59,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01993226151",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 39,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01103874554",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 6,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 10, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01628972878",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 29,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01892208909",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 58,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01294071028",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 63,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 6, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01487046076",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 19,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01114910988",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 7,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 8, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01926471374",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 23,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01701454061",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 58,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 4, United Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01352519969",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 55,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01268324283",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 27,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 1, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01290703412",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 34,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01934516381",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01888034534",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 33,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01873604508",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 19,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01661829251",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 27,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01935459068",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 50,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 3, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01558247767",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 45,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01896275796",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 34,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 3, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01216285753",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 41,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
];
