export const seedData = [
  {
    patientName: "Sharmin Akter",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, Evercare Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01924323636",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 8, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01554477662",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 3, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01422160698",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01751735969",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01199943266",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01984442700",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Alamdanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01532508955",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01647853793",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01336602176",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01725011755",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 10, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01575718182",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01147431678",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Chuadanga Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01930529203",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01106354701",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01492782480",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01806210094",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 1, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01315327620",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01528384101",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01934212676",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01827624979",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Damurhuda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 10, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01373550878",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01837635008",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 10, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01946465848",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01731563280",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01111629537",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 6, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01511187035",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01770998541",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Chuadanga",
    subDistrict: "Jibannagar",
    status: "Open",
    isSeed: true,
  },
];
