export const seedData = [
  {
    patientName: "Anwar Hossain",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 7, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01510784915",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 8, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01941335780",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01513339268",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01185295260",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 8, Kurmitola General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01120879748",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01804170751",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 5, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01213331935",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01299560567",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Batiaghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01687411390",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dacope",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 8, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01146077764",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dacope",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01973441870",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dacope",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01805320607",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dacope",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 10, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01375232825",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dacope",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01228287309",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dacope",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 1, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01594622818",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dacope",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01506853045",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 5, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01210953591",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01190387495",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 5, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01153696349",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01467994894",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 10, MH Samorita Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01726397316",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 9, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01521371366",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01336675463",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01344240337",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01973407239",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dighalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 8, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01633486866",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dumuria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01242610631",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dumuria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01778821582",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dumuria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01404592731",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dumuria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01502819659",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dumuria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01887390917",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Dumuria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 1, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01152890764",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Koyra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 10, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01123883074",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Koyra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01539718650",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Koyra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01497017751",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Koyra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01615948958",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Koyra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01766915144",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Koyra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 9, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01952108693",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Koyra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01457292919",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01626527048",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01218335255",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01195008974",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01591213405",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01336421449",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01403851041",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01144113365",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Paikgacha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Evercare Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01677322676",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01117720988",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01486515765",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01704846100",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01998674898",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01922167492",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01607811897",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 6, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01910950066",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Phultala",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Evercare Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01243785578",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01847025721",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01832935276",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01961907986",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01747638634",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 9, United Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01982369225",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01600636805",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01885569317",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01120116445",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 1, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01223173406",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Rupsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01860164892",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Terokhada",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01893261420",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Terokhada",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Square Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01693102736",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Terokhada",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 7, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01674679489",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Terokhada",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01651372188",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Terokhada",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 10, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01511298780",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Khulna",
    subDistrict: "Terokhada",
    status: "Open",
    isSeed: true,
  },
];
