export const seedData = [
  {
    patientName: "Arifa Sultana",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01951125783",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Bheramara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01300339962",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Bheramara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01347106382",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Bheramara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01714690750",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Bheramara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 3, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01812790473",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Bheramara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 8, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01862980320",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Bheramara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 7, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01395047931",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Bheramara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01280586456",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01657096979",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Marks Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01167734389",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01503102764",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 7, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01834073505",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 4, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01641378636",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 8, Central Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01927350680",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01599655287",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01854623944",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01482173986",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Daulatpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 3, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01932590242",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01185645616",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01181235977",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01125538655",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 9, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01687887104",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 8, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01864217533",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01771771661",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01528387833",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01309188509",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Khoksa",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01263711567",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kumarkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01449146480",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kumarkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01105306501",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kumarkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 8, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01876166881",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kumarkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 1, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01969575109",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kumarkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01310764025",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kumarkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01200508823",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kumarkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01604488469",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01275722144",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01473416988",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01407831674",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01129463832",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 10, United Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01759301257",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Monno Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01642637612",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01911204596",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Kushtia Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01594292425",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Mirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 7, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01667360557",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Mirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01199330276",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Mirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01620344288",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Mirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01442911555",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Mirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01326369228",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Kushtia",
    subDistrict: "Mirpur",
    status: "Open",
    isSeed: true,
  },
];
