export const seedData = [
  {
    patientName: "Nazma Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 9, BRB Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01572266879",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 51,
    patientGender: "Male",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 5, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01523521641",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 20,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 2, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01952153444",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 14,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01950780573",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 37,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01632997214",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 13,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01482990222",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 16,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01525738802",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 51,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 3, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01313415746",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 5,
    patientGender: "Male",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01673584663",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 43,
    patientGender: "Male",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01587223336",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 53,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Gangni",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 10, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01765033656",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 60,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01719519780",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 20,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01693982514",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01464830199",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 45,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 9, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01254290576",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 39,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 1, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01274986414",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 19,
    patientGender: "Male",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 5, Apollo Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01561519958",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 24,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01669161274",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 32,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 2, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01327902873",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 61,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01385322191",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 41,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Meherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01455601723",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 7,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01115067758",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 19,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, Marks Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01588257411",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 64,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01492600029",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 40,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01884201954",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 55,
    patientGender: "Other",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01572431894",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 10,
    patientGender: "Male",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01192441599",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 27,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 6, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01873280721",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 32,
    patientGender: "Female",
    division: "Khulna",
    district: "Meherpur",
    subDistrict: "Mujibnagar",
    status: "Open",
    isSeed: true,
  },
];
