export const seedData = [
  {
    patientName: "Zahid Hasan",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 10, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01199333452",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01213613254",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01675529983",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01103736921",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01673055346",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 10, Labaid Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01339884744",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Kalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01959199228",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 3, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01204593822",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01289512476",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01447375643",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01327927557",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01412943089",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01738086832",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 2, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01449523586",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01715452237",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Lohagara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 8, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01199764666",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01738788060",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01654856347",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01136707341",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01622704818",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 2, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01342413091",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01846380594",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Khulna",
    district: "Narail",
    subDistrict: "Narail Sadar",
    status: "Open",
    isSeed: true,
  },
];
