export const seedData = [
  {
    patientName: "Farhana Islam",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01752614026",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 2, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01618598615",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 8, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01876363541",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01134280449",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01735985186",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01597386078",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01687061087",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 9, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01303776235",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01913792492",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01441463723",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Jhalokati Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 7, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01435522389",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 8, Evercare Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01417999426",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01379194390",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01121008455",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01326599963",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01887477757",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01233214795",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01913004690",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01114470320",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01230253407",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Kanthalia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 9, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01215299923",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01580418572",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, Central Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01212970218",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 2, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01928824718",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01786626599",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 4, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01486176383",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01394818391",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01431273161",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Nalchity",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01388719676",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, MH Samorita Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01177513951",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 1, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01807136370",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01848181209",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01849259627",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 1, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01579942413",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01906181894",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 6, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01808636635",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Jhalokati",
    subDistrict: "Rajapur",
    status: "Open",
    isSeed: true,
  },
];
