export const seedData = [
  {
    patientName: "Anisur Rahman",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01606342834",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Bhandaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01381794739",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Bhandaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 10, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01661050795",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Bhandaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01390149989",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Bhandaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01598771351",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Bhandaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01693469019",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Indurkani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 8, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01880333213",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Indurkani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 6, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01318663399",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Indurkani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 3, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01649327850",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Indurkani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01752003891",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Indurkani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01343979267",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Kawkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 1, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01810438744",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Kawkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01889381785",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Kawkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 7, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01400677750",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Kawkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 10, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01347095656",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Kawkhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 1, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01383829578",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Mathbaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01604466458",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Mathbaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01680916400",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Mathbaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01933213125",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Mathbaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 7, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01610874000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Mathbaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01283607953",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Mathbaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 5, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01253589975",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01610693296",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01640551736",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01464746612",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01900165592",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01236880417",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01872706033",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 9, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01641873916",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 3, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01792698493",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nazirpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01850935414",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nesarabad (Swarupkati)",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01226017030",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nesarabad (Swarupkati)",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01831015472",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nesarabad (Swarupkati)",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01786967989",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nesarabad (Swarupkati)",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 6, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01823404624",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Nesarabad (Swarupkati)",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01662152002",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01265000200",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 4, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01336926856",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01743790761",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 2, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01128840392",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 3, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01295946262",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01615690731",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01367120154",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Barisal",
    district: "Pirojpur",
    subDistrict: "Pirojpur Sadar",
    status: "Open",
    isSeed: true,
  },
];
