export const seedData = [
  {
    patientName: "Saiful Islam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01433969577",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 28,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01263123351",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 62,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 7, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01601530483",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 33,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 10, Evercare Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01395993717",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 42,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01247032175",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 20,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01859153355",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 54,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01855555157",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 10,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01413993186",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 32,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01104204426",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 63,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01585749202",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 50,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01169167065",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 7,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01449384859",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 42,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01266945849",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 22,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01750320180",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 58,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01240992164",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 34,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01799956401",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 16,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01820274081",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 39,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 8, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01311725874",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 5, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01640373219",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01471070775",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 41,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01839813464",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 63,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01346236930",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 63,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01949056192",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 35,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01429014553",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01665320919",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 33,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 2, Labaid Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01629038138",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 35,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 3, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01752292720",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 6, Apollo Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01482820278",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 26,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01283286621",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 22,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01144933311",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01749943802",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 29,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01939075543",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 53,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01841580731",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 58,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01962413415",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 13,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01660373655",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 39,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01450766418",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 14,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
];
