export const seedData = [
  {
    patientName: "Sharmin Akter",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01451474170",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01875028727",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01161475549",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01298756607",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01643145756",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 9, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01282270918",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01581255690",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Bholahat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01207582454",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01824986525",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 1, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01185219446",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 4, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01801397187",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 4, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01859331541",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01457379951",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Chapainawabganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 1, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01132816717",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01598313529",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01763297799",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01620602915",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01503556412",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Gomastapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01484618435",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 2, Ibn Sina Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01356215653",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 9, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01228506392",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 1, Delta Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01897183214",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01323510390",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01718874057",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 7, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01821719776",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01509487749",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Central Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01977199886",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Nachole",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 1, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01703892793",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 9, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01382119261",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01437792956",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01242479994",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Labaid Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01193147921",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01559821488",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01401139347",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01133892297",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    division: "Rajshahi",
    district: "Chapainawabganj",
    subDistrict: "Shibganj",
    status: "Open",
    isSeed: true,
  },
];
