export const seedData = [
  {
    patientName: "Ferdousi Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01490919096",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 9,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01737197229",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 9,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 2, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01911324683",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 16,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01708360719",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 41,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01902775245",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 18,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Bagatipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 6, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01610293750",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 7,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01371026877",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 49,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 2, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01935435122",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 38,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01443718891",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 6,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 10, Evercare Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01546814634",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 5,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01300193353",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 25,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 4, Central Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01628712589",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 22,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Baraigram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01157819787",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 40,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 5, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01133173827",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 54,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01698018721",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 58,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01490796959",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 45,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 2, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01294308580",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Gurudaspur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01370791593",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 45,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Labaid Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01779677719",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 20,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01790364672",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 50,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01836522683",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 45,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 10, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01870477823",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 39,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 7, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01815508055",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 10,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Lalpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01313683842",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 14,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01176646557",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 18,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 6, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01890608530",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01529264310",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01198396058",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 46,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 9, Marks Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01497128048",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 37,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01602653030",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 11,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Natore Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01160554394",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 45,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01561719868",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 30,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01216999960",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 57,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01735759958",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 61,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01820987167",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 12,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Naldanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 1, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01667338274",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 51,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01555612259",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 15,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01655937136",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 16,
    patientGender: "Male",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01343788266",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 49,
    patientGender: "Other",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01139876884",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 31,
    patientGender: "Female",
    division: "Rajshahi",
    district: "Natore",
    subDistrict: "Singra",
    status: "Open",
    isSeed: true,
  },
];
