export const seedData = [
  {
    patientName: "Anwar Hossain",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 44,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 31,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 54,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 5,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 3, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 9, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 16,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 6,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 51,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 5,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 46,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 25,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 9, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 21,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 8, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 41,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 7, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 22,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 41,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 53,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 6, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 39,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 9, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 19,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 23,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 9, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 48,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 31,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 4, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 7,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 14,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 8, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 58,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 9, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 8, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 21,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 1, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 36,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 7, Apollo Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 5, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 63,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 1, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 33,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 8, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 55,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 7, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 44,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 14,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 12,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 6,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 9,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 1, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 25,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 43,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 2, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 46,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 57,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 33,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 7,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 10, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 58,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 24,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 42,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 21,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 43,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 7, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 35,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 6,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 9, Labaid Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 42,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 5, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 12,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 7, Evercare Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 10,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 7,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
];
