export const seedData = [
  {
    patientName: "Khadija Begum",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01492610039",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 37,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01970571936",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 21,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01254077109",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 44,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01948832132",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 25,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01467314411",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 9,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 4, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01235387441",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 23,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01706068523",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 17,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01612791948",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 16,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, Kurmitola General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01182281050",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 37,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Baksiganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 8, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01162138930",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 42,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01707355146",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 35,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 1, Monno Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01442451926",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 37,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01287719354",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 12,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01577003765",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 29,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01115327611",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 28,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01144493479",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 62,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01456061110",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 6,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 8, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01671682036",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 54,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01886565199",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 52,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Dewanganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01227046987",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 56,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01448020620",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 46,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01755585749",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 61,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01821381566",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 8,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01711743377",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 46,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Islampur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 6, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01149563343",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 36,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 3, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01573055818",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 38,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 6, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01935530969",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 40,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01519641287",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 44,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01153614025",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 62,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01683152356",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 34,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 9, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01824058360",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 40,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Jamalpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 3, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01745570038",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 14,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 10, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01802570627",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 57,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 6, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01559289866",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 11,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01494030666",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 46,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01126182664",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 35,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 3, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01747146504",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 39,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01314349569",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 12,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Madarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01899154869",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 5,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 2, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01650562323",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 37,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01573075281",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 25,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01102357055",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 58,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01785286454",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Melandaha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01484943117",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 6,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01521708644",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 59,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01418337081",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 45,
    patientGender: "female",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Monno Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01719615396",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 10,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 9, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01601185609",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 19,
    patientGender: "male",
    division: "Mymensingh",
    district: "Jamalpur",
    subDistrict: "Sarishabari",
    status: "Open",
    isSeed: true,
  },
];
