export const seedData = [
  {
    patientName: "Farhana Islam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 56,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 11,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 52,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 25,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 9,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 37,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 52,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 10, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 39,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 43,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 27,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Jhenaigati",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 9, Delta Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 54,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nakla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 50,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nakla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 4, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 36,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nakla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 15,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nakla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 10, BRB Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 51,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nakla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 54,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nakla",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 25,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, Delta Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 6,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 39,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 9, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 48,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 59,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 48,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 10, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 62,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 48,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 54,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Nalitabari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 21,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 19,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 24,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 28,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 1, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 23,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 20,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 11,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 40,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 57,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sherpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 39,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sreebardi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 18,
    patientGender: "Male",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sreebardi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sreebardi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 6, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 10,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sreebardi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Delta Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sreebardi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 37,
    patientGender: "Female",
    division: "Mymensingh",
    district: "Sherpur",
    subDistrict: "Sreebardi",
    status: "Open",
    isSeed: true,
  },
];
