export const seedData = [
  {
    patientName: "Khadija Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01148237515",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 39,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 6, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01703716469",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 24,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01490502723",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 26,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01240935199",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 14,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01273149216",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 40,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 3, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01298098117",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 2, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01292278187",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 25,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 1, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01348575721",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 46,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01483712212",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 10,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 7, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01292204899",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 32,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01134375554",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 48,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 9, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01999672170",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 8, Central Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01121707492",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 13,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 2, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01252918780",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 14,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01648088066",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 13,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01589779962",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 33,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Enam Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01295446010",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 7,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01316156340",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 17,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 5, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01697696556",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 42,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01738571710",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 43,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 4, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01840499489",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 48,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01248941658",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 6, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01434750307",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 6,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01438897390",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 43,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Evercare Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01567855182",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 29,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01923667064",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 40,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01621893629",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 29,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01885203743",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 8,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 6, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01715940866",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 14,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 10, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01701024398",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 6,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, BRB Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01423198419",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 23,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01173987964",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 31,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01270042538",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01545078738",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 23,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01211140974",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 9,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01343917902",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 62,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01272986747",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 40,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01180265689",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 15,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01907091836",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 13,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01621262892",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 39,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 9, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01465256264",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 35,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01918803352",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 58,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 7, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01324898708",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 62,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01708589037",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 38,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01345385581",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 21,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 2, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01220009542",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 46,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 3, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01235907288",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 7,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01753582653",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 41,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01923999991",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 18,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 5, Evercare Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01348825336",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 42,
    patientGender: "Other",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 6, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01890311886",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 47,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
];
