export const seedData = [
  {
    patientName: "Khadija Begum",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 32,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 1, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 37,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 57,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 6, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 5,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 33,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 16,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 8, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 54,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 24,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Fulchhari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 19,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 45,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 30,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 3, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 21,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 7, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 31,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 6, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 60,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 23,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 3, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 50,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 26,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 46,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gaibandha Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 32,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 10, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 24,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 41,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 59,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 54,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 42,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 5,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 57,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Gobindaganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 43,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 58,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 9, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 14,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 7, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 53,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 17,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 5, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 41,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 9, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 47,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 16,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Palashbari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 15,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 9, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 33,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 9, Apollo Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 38,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 15,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, MH Samorita Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 24,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sadullapur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 5, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 20,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 9,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 44,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 44,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 39,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 13,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 54,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Saghata",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 4, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 29,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 9, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 43,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 6,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 4, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 40,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 60,
    patientGender: "Female",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 5, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 21,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 2, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 15,
    patientGender: "Male",
    division: "Rangpur",
    district: "Gaibandha",
    subDistrict: "Sundarganj",
    status: "Open",
    isSeed: true,
  },
];
