export const seedData = [
  {
    patientName: "Jesmin Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01740999467",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 21,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01125603835",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 58,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 4, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01492317680",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 10,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 1, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01599644510",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 63,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 6, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01233723344",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 12,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01130275496",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 27,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 7, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01496217658",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01106707337",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 24,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Baliadangi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01216844976",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 39,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 9, Kurmitola General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01772156592",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 16,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 10, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01850828403",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 45,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01715608514",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 51,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01707298441",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 19,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01445402574",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 22,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01653280550",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 30,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01530294551",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 35,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Haripur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01249171832",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 50,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01345311177",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 53,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 6, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01228768078",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 60,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 7, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01979763337",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 42,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01638585727",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 23,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01504025171",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 55,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 9, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01541227141",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 62,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 1, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01601225862",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01433616711",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 52,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01771626367",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 42,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Pirganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 2, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01647120452",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 40,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Ranisankail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 9, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01589721250",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 25,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Ranisankail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01275945448",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 39,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Ranisankail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01803399495",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 57,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Ranisankail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01366588948",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "female",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Ranisankail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01765632499",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 33,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Ranisankail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01934257832",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 20,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Thakurgaon Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01368577729",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 23,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Thakurgaon Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 1, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01637176357",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 19,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Thakurgaon Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01244398024",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 21,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Thakurgaon Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01533182583",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 54,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Thakurgaon Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01285141828",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 24,
    patientGender: "male",
    division: "Rangpur",
    district: "Thakurgaon",
    subDistrict: "Thakurgaon Sadar",
    status: "Open",
    isSeed: true,
  },
];
