export const seedData = [
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 3, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01923582399",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 61,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Barlekha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 4, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01550054985",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 8,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Barlekha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 7, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01535806010",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 56,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Barlekha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01403536525",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 5,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Barlekha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01684385108",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 53,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Barlekha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01253903984",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 50,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Barlekha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01584437539",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 40,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Juri",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 9, Monno Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01345311072",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Juri",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01712835485",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 5,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Juri",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01428509329",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 36,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Juri",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 6, Marks Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01663286912",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 58,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Juri",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 7, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01598264977",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 61,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Juri",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 6, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01905595065",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 62,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Juri",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01564342987",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 30,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01509476684",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 7,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 6, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01780642931",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 46,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 10, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01317366387",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 25,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01209488789",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 30,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01777541803",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 36,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01565506860",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 28,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01101534296",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 42,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kamalganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 4, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01792821730",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 34,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kulaura",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01504132638",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 15,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kulaura",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01256550174",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 50,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kulaura",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 6, Enam Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01494327335",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 10,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kulaura",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01605676364",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Kulaura",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01631392804",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 11,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Moulvibazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01795341607",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 6,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Moulvibazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 8, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01128885842",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 58,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Moulvibazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01573377340",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 17,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Moulvibazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 1, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01872296728",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 28,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Moulvibazar Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01159998754",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 19,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01184396366",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 7,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01318119066",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 15,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01100474035",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 55,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 8, Labaid Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01527106939",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 14,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01959290132",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 42,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01328684562",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 35,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 9, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01924699498",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 39,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01703186125",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 32,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Rajnagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 3, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01989923643",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 55,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01399541896",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 48,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01808864574",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 40,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 4, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01793490008",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 44,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01354210142",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 9,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01294434549",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01273908568",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 49,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01351001354",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 21,
    patientGender: "Other",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01828279975",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 61,
    patientGender: "Female",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01692315138",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 5,
    patientGender: "Male",
    division: "Sylhet",
    district: "Moulvibazar",
    subDistrict: "Sreemangal",
    status: "Open",
    isSeed: true,
  },
];
