export const seedData = [
  {
    patientName: "Rafiqul Islam",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 62,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 34,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 9, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 12,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 10,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 63,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 4, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 12,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 19,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 9, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 9, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 29,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 30,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 10, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 34,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 52,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 51,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 6,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 1, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 15,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 34,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 1, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 61,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 7, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Kurmitola General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 44,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 48,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 5, Delta Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 41,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 4, Enam Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 27,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 6,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 41,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 30,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 10, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 57,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 22,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 10, Central Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 62,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 9, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 27,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 55,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 12,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 60,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 18,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 18,
    patientGender: "Male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 6,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 7, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 39,
    patientGender: "Female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
];
