export const seedData = [
  {
    patientName: "Jesmin Akter",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 7, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01796314118",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 19,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01802531152",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 59,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 3, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01429204402",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 17,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01742121170",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 49,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01702571022",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 51,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dhamrai",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01795388422",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 15,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01649823869",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 24,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 3, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01556161295",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 31,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01743558832",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 29,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 8, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01321351253",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 42,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01521628033",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 16,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01186208583",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 26,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01323007676",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 10,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Dohar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 6, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01652277898",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 8,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01829573880",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 60,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01757180162",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 26,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01933499525",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 30,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 9, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01518910663",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01278376178",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 13,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 6, Delta Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01636670888",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 38,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01181511532",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 60,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01798590779",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 62,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Keraniganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 4, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01106978765",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 13,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 7, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01480373922",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 29,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 7, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01579089568",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 10,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01996347777",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 27,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, Delta Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01636474963",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 19,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01685795892",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 47,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01345087162",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 61,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01750435687",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 55,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01690692543",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 15,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Nawabganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 10, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01166298485",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01950128809",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 15,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 9, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01239548511",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01239474627",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 36,
    patientGender: "male",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01658762690",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 35,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 4, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01846524832",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 36,
    patientGender: "female",
    division: "Dhaka",
    district: "Dhaka",
    subDistrict: "Savar",
    status: "Open",
    isSeed: true,
  },
];
