export const seedData = [
  {
    patientName: "Abul Kashem",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 9, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01639765308",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 26,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 5, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01365422416",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 28,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 8, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01296505997",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 8,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 5, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01711167493",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 58,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 10, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01405327251",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01873661784",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 59,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, BIRDEM General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01775366190",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 45,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01792826561",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Alfadanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01740496658",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 17,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Bhanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 7, Apollo Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01131921378",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 49,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Bhanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 7, BRB Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01983118128",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 24,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Bhanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 2, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01414636201",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 20,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Bhanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01154046593",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 53,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Bhanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 10, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01558929974",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 32,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Bhanga",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 2, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01886756413",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 52,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Boalmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01520133324",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 59,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Boalmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01736604562",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 13,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Boalmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01136164322",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 16,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Boalmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01871003899",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 52,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Boalmari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01368446334",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 25,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Charbhadrasan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 3, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01745863709",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 54,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Charbhadrasan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Apollo Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01141122566",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 26,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Charbhadrasan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01511107226",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 10,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Charbhadrasan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 3, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01375346851",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 36,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Charbhadrasan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01884073495",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 11,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Charbhadrasan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01560141435",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 59,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Charbhadrasan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01191774231",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 35,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01696701389",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 28,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 8, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01772675917",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 62,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01246180316",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 58,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01162338886",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 29,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 3, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01625835380",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 43,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 8, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01206133471",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 39,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 9, Labaid Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01709551998",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 36,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Faridpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01541241543",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01120644781",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 33,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 5, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01999723228",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 33,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 10, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01441331328",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 1, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01919770436",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 10,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01523726163",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 49,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01294243774",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 42,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 2, MH Samorita Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01462908119",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 64,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 5, BRB Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01890337165",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 42,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Madhukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01552611572",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 36,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Nagarkanda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 10, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01221724523",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 31,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Nagarkanda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01489443948",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 6,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Nagarkanda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01400293538",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 60,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Nagarkanda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 3, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01705146869",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 37,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Nagarkanda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 10, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01201305664",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 36,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Nagarkanda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01319952031",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 6,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Nagarkanda",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01549129021",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 41,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 8, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01412614980",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 17,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 6, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01670262536",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 52,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 8, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01279449293",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 35,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01785763334",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 54,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 9, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01275831820",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01835911098",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 6, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01507451285",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 46,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 8, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01700017620",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 58,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01439145701",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 37,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Sadarpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01182900260",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 33,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 3, Marks Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01647313414",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01822374034",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 19,
    patientGender: "Male",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01416508640",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 22,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01271823699",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 51,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01998184341",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 52,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01847377472",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 5,
    patientGender: "Female",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 3, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01911021428",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 62,
    patientGender: "Other",
    division: "Dhaka",
    district: "Faridpur",
    subDistrict: "Saltha",
    status: "Open",
    isSeed: true,
  },
];
