export const seedData = [
  {
    patientName: "Sharmin Akter",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01344758483",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 57,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 6, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01593077941",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 27,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01203492311",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 17,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01792945722",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 9, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01574086431",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 16,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 9, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01736148896",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 43,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01437729763",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 64,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01532624719",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01533408652",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 45,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01869210696",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 11,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01652479742",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 31,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01110588769",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 6,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 10, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01663104844",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 23,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 5, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01186584578",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 49,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01752645490",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 16,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01410186215",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 33,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01191407750",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 5, Ibn Sina Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01755526707",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 59,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 8, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01323236439",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 23,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01706247028",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 49,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01150407445",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 48,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 2, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01907435761",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 10,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 1, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01269255021",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01693126522",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 64,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01223387934",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 10,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 9, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01959687440",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 18,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 10, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01438965189",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 31,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 9, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01334797521",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 7, BRB Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01921956633",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 11,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 7, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01972303569",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 62,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 7, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01614063887",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 45,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01569298470",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 21,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01812580286",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 55,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01855620668",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 50,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 10, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01861997276",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 40,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01190359654",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 60,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 5, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01978864356",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 23,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01871521714",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 39,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 8, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01969644271",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 34,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 10, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01141464768",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 39,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Labaid Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01957539768",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 63,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 10, Square Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01472288285",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 48,
    patientGender: "Other",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
];
