export const seedData = [
  {
    patientName: "Bilkis Banu",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 8, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01572551941",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 31,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 3, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01233535832",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 19,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01746280074",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 24,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01199633392",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 9,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01531546719",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 37,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01120052389",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 22,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01325415533",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 29,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 6, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01709778567",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 52,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Gazipur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 2, Khulna Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01246348577",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 10,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 10, United Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01877344912",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 49,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 8, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01714577274",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 27,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01146183341",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 37,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01863085995",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 5,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01760478932",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 43,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 10, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01487697978",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 19,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01335568134",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 29,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 10, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01707467524",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 29,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliakair",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01851635943",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 9,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 2, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01558981603",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 39,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 10, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01203941707",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 32,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 6, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01604045072",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 7,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01211866198",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 15,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kaliganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 5, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01553913561",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 7,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 8, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01808813936",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 13,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01180627257",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 61,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01291966328",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 45,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 3, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01867971790",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 57,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 10, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01545091703",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 1, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01750866687",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 27,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01698285875",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 16,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01972447041",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 34,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Kapasia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 5, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01467477880",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 23,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01239584120",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 38,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 3, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01569996495",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 5,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01409963508",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 22,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01988459479",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 31,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 8, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01145361339",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 63,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01115017113",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 31,
    patientGender: "female",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01684972858",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 10,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 8, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01220113075",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 27,
    patientGender: "male",
    division: "Dhaka",
    district: "Gazipur",
    subDistrict: "Sreepur",
    status: "Open",
    isSeed: true,
  },
];
