export const seedData = [
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 9, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 37,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 29,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 16,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 8,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Apollo Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 29,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Gopalganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 39,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 5, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 7,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 19,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, Monno Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 26,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 10, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kashiani",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 9, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 50,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 7, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 8,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 7, Kurmitola General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 39,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 36,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 8, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 52,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 9, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 61,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Kotalipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 62,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 52,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 38,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 6, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 24,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 55,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 29,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, Mugda Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 58,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 5, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 26,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Muksudpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 10, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 55,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 52,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 4, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 50,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 10,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 7, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 47,
    patientGender: "Female",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 4, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01700000000",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 55,
    patientGender: "Male",
    division: "Dhaka",
    district: "Gopalganj",
    subDistrict: "Tungipara",
    status: "Open",
    isSeed: true,
  },
];
