export const seedData = [
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Evercare Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01424996214",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Austagram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 7, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01190560726",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 38,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Austagram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 3, Evercare Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01822830576",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 41,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Austagram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 3, Popular Diagnostic Centre area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01163363795",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Austagram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01533920822",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 38,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Austagram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01564295909",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 15,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Austagram",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 9, Marks Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01163826892",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 15,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bajitpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 3, Ibn Sina Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01506344103",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 56,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bajitpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01714283904",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 21,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bajitpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 7, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01400228573",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 7,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bajitpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 8, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01514103957",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 34,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bajitpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 9, Kurmitola General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01236584809",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 10,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bajitpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01919131677",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 42,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bajitpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 1, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01731910503",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 54,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01751709807",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 16,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 9, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01112412361",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 49,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01652298966",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 5,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 1, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01764933239",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 38,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01360088078",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01432133274",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 36,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01574530304",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 61,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 3, Evercare Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01664639104",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 39,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Bhairab",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 10, MH Samorita Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01703349009",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 40,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Hossainpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01428061602",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 43,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Hossainpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01907622600",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 39,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Hossainpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01961009548",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 46,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Hossainpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01374647951",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 8,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Hossainpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, BRB Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01141142217",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 40,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Hossainpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, Monno Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01800656405",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 15,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Hossainpur",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 6, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01197777467",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 40,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Itna",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 8, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01831554757",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 23,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Itna",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01553322009",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 57,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Itna",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, BRB Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01124981565",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 54,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Itna",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 6, Central Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01493971157",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 60,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Itna",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01597299035",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 19,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Itna",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01813694689",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 41,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Itna",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 5, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01777019030",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 26,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 7, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01685913276",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 5,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 5, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01960358026",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 11,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01596356722",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 57,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01548539682",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 47,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 8, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01745361988",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 25,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01561551431",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 64,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 6, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01419394005",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01331416522",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 22,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Karimganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 10, Labaid Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01757531380",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 50,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Katiadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 6, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01719185728",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 16,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Katiadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01808361606",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 14,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Katiadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01809937967",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 9,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Katiadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 2, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01905991000",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 20,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Katiadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 1, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01850058530",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 22,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Katiadi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 7, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01986528180",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 8,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kishoreganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01834039577",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 53,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kishoreganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 1, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01681356838",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 9,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kishoreganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01190338187",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 34,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kishoreganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01324660958",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 25,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kishoreganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01694472113",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 36,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kishoreganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Monno Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01669022339",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 8,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kuliarchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01547876021",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 12,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kuliarchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 6, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01611473245",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kuliarchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01324749210",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 23,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kuliarchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01217928392",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 12,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Kuliarchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01387556845",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 59,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01810234640",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 41,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01117757760",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 27,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 3, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01311471910",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 7,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01359263579",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 43,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 7, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01545221844",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 45,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 7, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01114794174",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 48,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01943732688",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 24,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01594181549",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 18,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 2, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01705671401",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 5,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Mithamain",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 10, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01758085020",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 64,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Nikli",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01800746943",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 37,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Nikli",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 5, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01858834430",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 43,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Nikli",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01301643338",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 23,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Nikli",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01326876722",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 35,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Nikli",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 2, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01747693902",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 52,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01923230211",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 37,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 3, Square Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01882301290",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 20,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 7, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01815460373",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 63,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01326639795",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 54,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01801011810",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 56,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 1, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01358881445",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 13,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 9, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01827528715",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 47,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 9, BRB Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01309986649",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 62,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 7, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01329297532",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Pakundia",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 7, Labaid Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01593744061",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 23,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Tarail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 8, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01437947298",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 23,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Tarail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01489352884",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 54,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Tarail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 6, BRB Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01496147096",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 17,
    patientGender: "male",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Tarail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 7, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01887436906",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 48,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Tarail",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Labaid Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01256805177",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 24,
    patientGender: "female",
    division: "Dhaka",
    district: "Kishoreganj",
    subDistrict: "Tarail",
    status: "Open",
    isSeed: true,
  },
];
