export const seedData = [
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 3, Apollo Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01241592045",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 64,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01890484403",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 51,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01242957430",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 30,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01294782359",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 30,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01262611402",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 10,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 9, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01566804868",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 53,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01770525281",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 53,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01903824348",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 32,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Kalkini",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 6, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01990806554",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 62,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Madaripur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 2, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01510598204",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 47,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Madaripur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 9, BIRDEM General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01186854230",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 31,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Madaripur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01529306109",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 55,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Madaripur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01731271563",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 48,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Madaripur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 5, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01996523374",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 30,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Madaripur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 1, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01971486082",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 10,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Madaripur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 10, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01275637520",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 17,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 4, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01805310606",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 52,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 7, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01354649933",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 50,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01298484892",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 34,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 10, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01709053358",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 16,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01162618880",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 42,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 3, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01493531669",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 18,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 1, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01515775595",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 11,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01669267647",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 61,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 10, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01401959055",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 44,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Rajoir",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 5, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01474534623",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 43,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01808341168",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 62,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Mugda Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01719384891",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 64,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01398067158",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 62,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 7, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01915801268",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Monno Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01923671718",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 25,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01396369621",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 57,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01850343783",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 30,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 6, Ibn Sina Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01573394077",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 60,
    patientGender: "male",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 10, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01248785924",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 28,
    patientGender: "female",
    division: "Dhaka",
    district: "Madaripur",
    subDistrict: "Shibchar",
    status: "Open",
    isSeed: true,
  },
];
