export const seedData = [
  {
    patientName: "Azizul Haque",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01678878366",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 37,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 5, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01762342189",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 25,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 2, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01525528464",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01686330807",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 37,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 4, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01676035855",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Thalassemia",
    patientAge: 36,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 2, Evercare Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01753881925",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 15,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 2, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01543620873",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 64,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01585301141",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 14,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 3, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01475189452",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 47,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Gazaria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 5, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01925734134",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 36,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Lohajang",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01306106268",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 29,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Lohajang",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01157123366",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 13,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Lohajang",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 6, Square Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01795495800",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 56,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Lohajang",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 2, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01779843588",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 52,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Lohajang",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01844535382",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 30,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Lohajang",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01936707892",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 54,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Munshiganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 10, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01516247374",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 23,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Munshiganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 10, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01103474398",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 45,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Munshiganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, United Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01106925810",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 10,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Munshiganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 8, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01123351721",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 49,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Munshiganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01945581577",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 51,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Munshiganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 8, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01865397174",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 23,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sirajdikhan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01900244849",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 19,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sirajdikhan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 4, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01972651165",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 6,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sirajdikhan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01569917693",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 40,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sirajdikhan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 5, United Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01658578716",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 27,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sirajdikhan",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01215426702",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 19,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sreenagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 9, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01256210717",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 37,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sreenagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 2, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01841381573",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 9,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sreenagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01586753636",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 34,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sreenagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01688181261",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 56,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sreenagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Ibn Sina Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01469510260",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Cancer Treatment",
    patientAge: 21,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sreenagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 2, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01793176036",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 34,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Sreenagar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jesmin Akter",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01377087980",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 61,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 9, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01856782363",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 38,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01831615465",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 36,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01561359785",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 30,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 2, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01653157109",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 49,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 3, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01394446313",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 40,
    patientGender: "Other",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 2, Labaid Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01899362947",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 8,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 3, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01688372742",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 14,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 1, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01426307854",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 15,
    patientGender: "Male",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01344263169",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 47,
    patientGender: "Female",
    division: "Dhaka",
    district: "Munshiganj",
    subDistrict: "Tongibari",
    status: "Open",
    isSeed: true,
  },
];
