export const seedData = [
  {
    patientName: "Saiful Islam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 3, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01796033353",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 8,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Square Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01454851222",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 9, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01295326601",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 52,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 7, Central Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01187775134",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 21,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 4, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01222343285",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 16,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 4, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01562307906",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 39,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 2, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01924038074",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 7, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01993694686",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 8,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, Central Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01720999675",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 7, Evercare Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01432759668",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 33,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01986532903",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 40,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01318164938",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 55,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01839688218",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 19,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 2, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01381857759",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 4, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01820582967",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 45,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 2, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01819111552",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 49,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 6, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01830251015",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 32,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 10, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Low",
    contactNumber: "01574258381",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 7,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 5, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01382540240",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 28,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 8, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01824125234",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 21,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01309850507",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 53,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shafiqul Alam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 9, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01784051308",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 58,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 5, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01820697508",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 60,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01999531062",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 42,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 8, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01388318246",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 57,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 1, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01876537963",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 53,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 5, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01545477137",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 43,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 1, Marks Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01125897205",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 1, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01890155480",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 13,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01289268017",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 11,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01636157943",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 45,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 6, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01907573296",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 35,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 1, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01168805029",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 63,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 10, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01209675659",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 55,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 1, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01166289235",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 56,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 9, Dhaka Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01168259476",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 14,
    patientGender: "male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01528826017",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 34,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 7, MH Samorita Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01688183929",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 32,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 5, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01986925414",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 6,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01308960000",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 15,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 10, Delta Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01197214740",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 17,
    patientGender: "female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
];
