export const seedData = [
  {
    patientName: "Farhana Islam",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 7, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01470135293",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 50,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01592331653",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 64,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 4, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01365466953",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 49,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 10, Khulna Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01643591267",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 59,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 6, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01113080414",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 18,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 8, Apollo Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01488026784",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 60,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 8, BIRDEM General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01670266992",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 9,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 6, Kurmitola General Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01506452335",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 18,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 9, BIRDEM General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01920234524",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 32,
    patientGender: "Other",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Araihazar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Evercare Hospital",
    hospitalLocation: "Ward 4, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01272282361",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Thalassemia",
    patientAge: 45,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 5, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01735464679",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 25,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Monno Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01448899855",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 14,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 1, BRB Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01457738364",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 48,
    patientGender: "Other",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Sir Salimullah Medical College Hospital",
    hospitalLocation: "Ward 8, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01986334922",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 31,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 2, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01578459857",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 64,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 8, United Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01768938745",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 58,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Monno Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01787405018",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 22,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 5, Square Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01499982070",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Cancer Treatment",
    patientAge: 63,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01689938258",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Cancer Treatment",
    patientAge: 59,
    patientGender: "Other",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Bandar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 4, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01877991271",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 18,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    hospitalLocation: "Ward 9, Enam Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01379135076",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 25,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 1, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01593620851",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 17,
    patientGender: "Other",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 10, Popular Diagnostic Centre area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01278891220",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 58,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01827186873",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 26,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 9, Evercare Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01496713205",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 61,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sabina Yasmin",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 3, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01145825690",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Cancer Treatment",
    patientAge: 46,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Narayanganj Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01592722038",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Thalassemia",
    patientAge: 48,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 1, Popular Diagnostic Centre area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01241882444",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 6,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01419948237",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 63,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 8, Labaid Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01432682002",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 9,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 6, Evercare Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01308939069",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 64,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01791217468",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 64,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 4, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01367074739",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 44,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Khadija Begum",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01365828513",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 36,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Green Life Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01192489831",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 59,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Rupganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 4, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01894228667",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 56,
    patientGender: "Male",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Aminul Islam",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01834890331",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 63,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 5, BRB Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01617692768",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 46,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 4, Comilla Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Critical",
    contactNumber: "01719861426",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Thalassemia",
    patientAge: 55,
    patientGender: "Other",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Delta Hospital",
    hospitalLocation: "Ward 6, Holy Family Red Crescent Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01595837565",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 41,
    patientGender: "Female",
    division: "Dhaka",
    district: "Narayanganj",
    subDistrict: "Sonargaon",
    status: "Open",
    isSeed: true,
  },
];
