export const seedData = [
  {
    patientName: "Aminul Islam",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 9, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01110067969",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 62,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Baliakandi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 4, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01389595861",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 63,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Baliakandi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 7, Delta Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01332981819",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 30,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Baliakandi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 1, Rangpur Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01737123312",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 57,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Baliakandi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 4, Ibn Sina Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Critical",
    contactNumber: "01747036361",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 63,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Baliakandi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01505266717",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 32,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Baliakandi",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 4, Square Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01187927290",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 7,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 10, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01366474224",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 19,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 4, MH Samorita Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01968265861",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 32,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Monir Hossain",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 10, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01972747026",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 52,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, BRB Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01333894121",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 46,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sadia Afrin",
    hospitalName: "BRB Hospital",
    hospitalLocation: "Ward 7, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01882685090",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 8,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahnaz Parvin",
    hospitalName: "Bangladesh Specialized Hospital",
    hospitalLocation: "Ward 7, Kurmitola General Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01982664643",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 29,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Labaid Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01180661567",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 26,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 5, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01213233266",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 44,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Goalandaghat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 9, Square Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01646570427",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 42,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Kalukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rezaul Karim",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01688123197",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 8,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Kalukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Comilla Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01846571502",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 18,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Kalukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 2, Labaid Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01795487131",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 48,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Kalukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 6, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01303560186",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 22,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Kalukhali",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "United Hospital",
    hospitalLocation: "Ward 6, Apollo Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01222218675",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 55,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Pangsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Kamrul Hassan",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 6, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01337841376",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 29,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Pangsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 8, Enam Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Low",
    contactNumber: "01367230647",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 11,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Pangsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 9, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01290093158",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 49,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Pangsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01950538868",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 36,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Pangsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 6, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01391202335",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 26,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Pangsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Azizul Haque",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 4, Marks Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01879888646",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 44,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Pangsha",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 6, Labaid Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "High",
    contactNumber: "01481630426",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 62,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Rajbari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Jahangir Alam",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 7, Green Life Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01929599470",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 8,
    patientGender: "male",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Rajbari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nusrat Jahan",
    hospitalName: "MH Samorita Hospital",
    hospitalLocation: "Ward 5, Kurmitola General Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01980290109",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 61,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Rajbari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 1, Enam Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01200637328",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 31,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Rajbari Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Ad-din Medical College Hospital",
    hospitalLocation: "Ward 6, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01490622908",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 14,
    patientGender: "female",
    division: "Dhaka",
    district: "Rajbari",
    subDistrict: "Rajbari Sadar",
    status: "Open",
    isSeed: true,
  },
];
