export const seedData = [
  {
    patientName: "Kohinoor Akter",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 1, Rajshahi Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01878738981",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 9,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 4, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01924141840",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 20,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shamima Nasrin",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 7, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Medium",
    contactNumber: "01187435410",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 57,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 2, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01964723578",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 61,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Asif Iqbal",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 8, Delta Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01470530357",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 42,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 4, Mugda Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01422442438",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 21,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Bilkis Banu",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 4, Delta Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "Low",
    contactNumber: "01336303295",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 23,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tania Ahmed",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 5, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "Medium",
    contactNumber: "01314365396",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 58,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 10, Chittagong Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01434529191",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 61,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 1, Central Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01602437304",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 13,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Bhedarganj",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Meherun Nesa",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 7, Bangabandhu Sheikh Mujib Medical University area",
    bloodTypeNeeded: "O+",
    urgency: "High",
    contactNumber: "01164515253",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 6,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sumaiya Khan",
    hospitalName: "Mymensingh Medical College Hospital",
    hospitalLocation: "Ward 6, United Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01406245252",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 29,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Zainul Haque Sikder Women's Medical College & Hospital",
    hospitalLocation: "Ward 8, Comilla Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01621327820",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 8,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Ferdousi Begum",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 6, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "High",
    contactNumber: "01676676055",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 60,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 7, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Medium",
    contactNumber: "01104265922",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 28,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Sharmin Akter",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 3, Anwer Khan Modern Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01869658535",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 45,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 5, National Institute of Cancer Research & Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01736642455",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 41,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "National Institute of Cancer Research & Hospital",
    hospitalLocation: "Ward 2, Marks Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01228564227",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 36,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Damudya",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Farhana Islam",
    hospitalName: "Holy Family Red Crescent Medical College Hospital",
    hospitalLocation: "Ward 9, Zainul Haque Sikder Women's Medical College & Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01159575259",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 18,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Gosairhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 10, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01170878417",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 11,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Gosairhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Green Life Medical College Hospital",
    hospitalLocation: "Ward 10, United Hospital area",
    bloodTypeNeeded: "B+",
    urgency: "High",
    contactNumber: "01573099432",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 6,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Gosairhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 1, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01198727350",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 16,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Gosairhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Khulna Medical College Hospital",
    hospitalLocation: "Ward 10, BIRDEM General Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01944093710",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 36,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Gosairhat",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mahbubur Rahman",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01849933482",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 53,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Jajira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Humayun Kabir",
    hospitalName: "Anwer Khan Modern Medical College Hospital",
    hospitalLocation: "Ward 4, Bangladesh Specialized Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Low",
    contactNumber: "01559656185",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 56,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Jajira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Zahid Hasan",
    hospitalName: "Enam Medical College Hospital",
    hospitalLocation: "Ward 4, BIRDEM General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01841335098",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 29,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Jajira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Saiful Islam",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 8, Central Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01903075259",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 64,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Jajira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Tanvir Ahmed",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 10, Ad-din Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "High",
    contactNumber: "01185493662",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 55,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Jajira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Fatema Tuz Zohra",
    hospitalName: "Square Hospital",
    hospitalLocation: "Ward 7, Popular Diagnostic Centre area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01573025593",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 60,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Jajira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mizanur Chowdhury",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 4, Central Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Low",
    contactNumber: "01827844157",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 49,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Jajira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 7, BRB Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01566903906",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 44,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 3, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01301282040",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 9,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Labaid Hospital",
    hospitalLocation: "Ward 7, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01925043564",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 29,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Abul Kashem",
    hospitalName: "Rajshahi Medical College Hospital",
    hospitalLocation: "Ward 9, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "High",
    contactNumber: "01961572741",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 6,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 1, Sir Salimullah Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01881615820",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 61,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Mostafa Kamal",
    hospitalName: "Mugda Medical College Hospital",
    hospitalLocation: "Ward 2, Mugda Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Critical",
    contactNumber: "01477953374",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Accident",
    patientAge: 60,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rina Begum",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 9, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Critical",
    contactNumber: "01234575554",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Other",
    patientAge: 47,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Golam Mostafa",
    hospitalName: "Bangabandhu Sheikh Mujib Medical University",
    hospitalLocation: "Ward 2, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01396147044",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Accident",
    patientAge: 39,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Chittagong Medical College Hospital",
    hospitalLocation: "Ward 10, Shaheed Suhrawardy Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Medium",
    contactNumber: "01148017785",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Other",
    patientAge: 46,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Naria",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Shaheed Suhrawardy Medical College Hospital",
    hospitalLocation: "Ward 8, MH Samorita Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Medium",
    contactNumber: "01310172975",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 30,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Shariatpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anisur Rahman",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 3, Kurmitola General Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Critical",
    contactNumber: "01294964210",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 29,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Shariatpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Arifa Sultana",
    hospitalName: "Apollo Hospital",
    hospitalLocation: "Ward 2, Delta Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Medium",
    contactNumber: "01570364167",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 7,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Shariatpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Anwar Hossain",
    hospitalName: "Kurmitola General Hospital",
    hospitalLocation: "Ward 5, Khulna Medical College Hospital area",
    bloodTypeNeeded: "O+",
    urgency: "Critical",
    contactNumber: "01570161697",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Operation",
    patientAge: 45,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Shariatpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Habibur Rahman",
    hospitalName: "Comilla Medical College Hospital",
    hospitalLocation: "Ward 10, Apollo Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Critical",
    contactNumber: "01955550829",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Other",
    patientAge: 42,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Shariatpur Sadar",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nazma Begum",
    hospitalName: "Monno Medical College Hospital",
    hospitalLocation: "Ward 9, Sylhet MAG Osmani Medical College Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01574000195",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Operation",
    patientAge: 55,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Rangpur Medical College Hospital",
    hospitalLocation: "Ward 4, Apollo Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Low",
    contactNumber: "01654169014",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Other",
    patientAge: 48,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "Sylhet MAG Osmani Medical College Hospital",
    hospitalLocation: "Ward 6, Khulna Medical College Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "Critical",
    contactNumber: "01204117348",
    phoneNumber: "01700000000",
    numberOfBags: 2,
    cause: "Delivery",
    patientAge: 52,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Popular Diagnostic Centre",
    hospitalLocation: "Ward 10, Sher-e-Bangla Medical College Hospital area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01789927972",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Delivery",
    patientAge: 26,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nilufar Yasmin",
    hospitalName: "Ibn Sina Hospital",
    hospitalLocation: "Ward 8, Ibn Sina Hospital area",
    bloodTypeNeeded: "O-",
    urgency: "Low",
    contactNumber: "01294358576",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Accident",
    patientAge: 63,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rafiqul Islam",
    hospitalName: "Dhaka Medical College Hospital",
    hospitalLocation: "Ward 3, Mymensingh Medical College Hospital area",
    bloodTypeNeeded: "AB+",
    urgency: "Medium",
    contactNumber: "01665411528",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Delivery",
    patientAge: 48,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Shahadat Hossain",
    hospitalName: "Central Hospital",
    hospitalLocation: "Ward 5, Marks Medical College Hospital area",
    bloodTypeNeeded: "B-",
    urgency: "Medium",
    contactNumber: "01648820761",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Operation",
    patientAge: 12,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Rokeya Sultana",
    hospitalName: "National Institute of Cardiovascular Diseases",
    hospitalLocation: "Ward 9, National Institute of Cardiovascular Diseases area",
    bloodTypeNeeded: "A+",
    urgency: "Low",
    contactNumber: "01717806113",
    phoneNumber: "01700000000",
    numberOfBags: 3,
    cause: "Operation",
    patientAge: 58,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Nasir Uddin",
    hospitalName: "Marks Medical College Hospital",
    hospitalLocation: "Ward 2, BRB Hospital area",
    bloodTypeNeeded: "A-",
    urgency: "High",
    contactNumber: "01240264128",
    phoneNumber: "01700000000",
    numberOfBags: 4,
    cause: "Delivery",
    patientAge: 16,
    patientGender: "male",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
  {
    patientName: "Salma Khatun",
    hospitalName: "BIRDEM General Hospital",
    hospitalLocation: "Ward 6, BRB Hospital area",
    bloodTypeNeeded: "AB-",
    urgency: "High",
    contactNumber: "01835940010",
    phoneNumber: "01700000000",
    numberOfBags: 1,
    cause: "Accident",
    patientAge: 33,
    patientGender: "female",
    division: "Dhaka",
    district: "Shariatpur",
    subDistrict: "Zanjira",
    status: "Open",
    isSeed: true,
  },
];
